### PR TITLE
Introduce .envrc.local

### PR DESCRIPTION
**Pull request by 0xrin1**
- Introduce .envrc.local for local vs staging .direnv
- Adds `source .envrc.local` to end of .envrc so .envrc.local overrides values if present

### CODE REVIEW

**Review by joaop21 — COMMENTED** [review]
Yes, this is useful, but it works assuming that `dotenv` exists, which may not be true.
Why not a generic approach like `source ".envrc.local"`?

**Comment by 0xrin1** [comment]
> Yes, this is useful, but it works assuming that `dotenv` exists, which may not be true. Why not a generic approach like `source ".envrc.local"`?

Nice idea, implemented :+1:

**Comment by 0xrin1** [comment]
> I'm not sure why you removed the check for the file existence. You should still check if the file exists as you did. It would end up in something like `[[ -f .envrc.local ]] && source .envrc.local`, right?

readded :tada:

**Comment by joaop21** [comment]
I tested this locally, but it failed due to the `POLY_RPC_URL` value that needs to be a WSS URL. The main branch has a valid one.

**Comment by 0xrin1** [comment]
> I tested this locally, but it failed due to the `POLY_RPC_URL` value that needs to be a WSS URL. The main branch has a valid one.

Nice catch I made the change and corrected the fallback values on the providers since they were falling back to http not wss :+1:

tbh we should probably support both types of providers since we're not listening to contract events but we can do that in another PR

**Review by joaop21 — APPROVED** [review]

**Pull request merged**
