### PR TITLE
Update alreadyRun

### PR DESCRIPTION
**Pull request by joaop21**
Context:
`collectPerformance` is a job that runs every hour and writes the vault metrics to database. Even though this job was always completed successfully, it only writes to database every two hours, which is not consistent with our logic. It turns out that our function `alreadyRun` checks if a job with a given name already ran in the last hour (in this case) but it takes into account the millisecond part of the timestamp which is kinda tricky and could raise some issues.

This PR solves this issue by truncating the timestamps to seconds in the query that checks if a job already ran in the last hourly interval.

### CODE REVIEW

**Comment by gabrielpoca** [comment]
@joaop21 what issues? I don't understand xD

**Comment by joaop21** [comment]
> @joaop21 what issues? I don't understand xD

I will try to detail this issue the best I can. 😅 

1. Every hour there is a job to collect the performance of the Vault.
1. This job checks if there is an execution of a job with the same name in the past hour:
    1.  If no job is found, then the current job runs `collectPerformance` and writes the vault performance value to the database.
    1.  If any job is found, it is because an identical job has recently been executed and so the current job completes its execution without actually executing `collectPerformance`. 

The problem here is that by using the entire timestamp to check if an hour has passed, we incur the error of failing by mere milliseconds, and cause `collectPerformance` to never execute after a database write in the previous hour. This results in the vault performance value being written every two hours, which is precisely what is happening.
The database process that happens every hour is based on a read (of the most recent timestamp) preceding a write (of the new job execution) where there is a small-time lag (of milliseconds) between the two, which is enough for the next hour's check to fail.

But, giving a specific example:
1 - The last `collectPerformance` entry is written to database at `2022-05-25 12:00:00.50000`;
2 - The job that runs in the next hour first checks for the existence of some job that ran in the previous hour, and this read obviously precedes the write, so if it happens, for example, at `2022-05-25 13:00:00.00.25000`, that causes the job to confirm the existence of a recent job and therefore completes without actually running.

By using the whole timestamp we are making a very strong temporal assumption, which I think can be made easier by truncating the timestamp to seconds.

**Comment by gabrielpoca** [comment]
@joaop21 but that's the expected behaviour. There are many scenarios that can lead to that, for instance, if the server is restarted 1 second before the time to execute. If you need more precision, just change the execution interval to 30, or 15 minutes. That should be enough to ensure that there's at least a capture every 1:15, no?

**Comment by joaop21** [comment]
@gabrielpoca yes, I believe you're right and that's expected behaviour. But given that we have an endpoint which is `/api/metrics/hour`, I wanted to make sure that we were consistent and actually retrieve information of every hour. Running this job more often is the simplest option, maybe once every half hour.

**Pull request closed without merging**
